# source: https://raw.githubusercontent.com/ingenue/hunter/pkg.template/.travis.yml

# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - python3-pip

      - g++-5
      - gcc-5

dist:
  - trusty

matrix:
  include:
    # Linux {
    - os: linux
      env: CONFIG=Release TOOLCHAIN=default TEST=--test
    - os: linux
      env: CONFIG=Release TOOLCHAIN=clang-libstdcxx TEST=--test
    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5 TEST=--test
    - os: linux
      env: CONFIG=Release TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon TEST=
    - os: linux
      env: CONFIG=Release TOOLCHAIN=android-ndk-r15c-api-21-armeabi-v7a-neon-clang-libcxx TEST=
    # libjpeg failure:
    # - os: linux
    #   env: CONFIG=Release TOOLCHAIN=analyze
    - os: linux
      env: CONFIG=Release TOOLCHAIN=sanitize-address TEST=--test
    - os: linux
      env: CONFIG=Release TOOLCHAIN=sanitize-leak TEST=--test
    - os: linux
      env: CONFIG=Release TOOLCHAIN=sanitize-thread TEST=--test
    # }

    # OSX {
    - os: osx
      env: CONFIG=Release TOOLCHAIN=libcxx TEST=--test
    - os: osx
      env: CONFIG=Release TOOLCHAIN=osx-10-12 TEST=--test
    - os: osx
      env: CONFIG=Release TOOLCHAIN=ios-nocodesign-10-3 TEST=
    # }

install:
  - source bin/hunter_env.sh

script:
  - polly.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose --fwd HUNTER_SUPPRESS_LIST_OF_FILES=ON HUNTER_USE_CACHE_SERVERS=ONLY HUNTER_DISABLE_BUILDS=ON CVSTEER_BUILD_TEST=ON ${TEST} --install --discard 10 --tail 200
  
# https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
    - /^pr\..*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/


