# Source: https://raw.githubusercontent.com/ingenue/hunter/pkg.opencv/appveyor.yml

image: Visual Studio 2015

environment:

  matrix:

    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Release

install:
  - cmd: bin\hunter_env.cmd
  
build_script:
  - cmd: python %POLLY_ROOT%\bin\polly.py --toolchain "%TOOLCHAIN%" --config "%CONFIG%" --verbose --fwd HUNTER_SUPPRESS_LIST_OF_FILES=ON HUNTER_USE_CACHE_SERVERS=ONLY HUNTER_DISABLE_BUILDS=ON CVSTEER_BUILD_TEST=ON --install --discard 10 --tail 200

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
    - /^pr\..*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/