### OpenCV

set(OPENCV_CMAKE_ARGS
  BUILD_ANDROID_EXAMPLES=OFF 
  BUILD_DOCS=OFF 
  BUILD_EXAMPLES=OFF 
  BUILD_PERF_TESTS=OFF 
  BUILD_TESTS=OFF 
  BUILD_opencv_apps=OFF 
  INSTALL_PYTHON_EXAMPLES=OFF  
  BUILD_WITH_STATIC_CRT=OFF 
  BUILD_ZLIB=OFF 
  BUILD_TIFF=OFF 
  BUILD_JPEG=OFF
  WITH_JPEG=OFF 
  BUILD_PNG=OFF
  )

hunter_config(OpenCV VERSION ${HUNTER_OpenCV_VERSION} CMAKE_ARGS "${OPENCV_CMAKE_ARGS}")




